# 559x374 (209066)
mesh:
- direction: x
  start: -16.5
  subDomains:
  - cells: 128
    end: -5.0
    stretchRatio: 0.9803921569
  - cells: 300
    end: 1.0
    stretchRatio: 1.0
  - cells: 131
    end: 13.5
    stretchRatio: 1.02
- direction: y
  start: -15.0
  subDomains:
  - cells: 137
    end: -1.0
    stretchRatio: 0.9803921569
  - cells: 100
    end: 1.0
    stretchRatio: 1.0
  - cells: 137
    end: 15.0
    stretchRatio: 1.02

flow:
  nu: 0.025
  initialVelocity: [0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: yMinus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.0005
  startStep: 0
  nt: 7000
  nsave: 1000
  nrestart: 7000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  delta: ROMA_ET_AL_1999
  lietal2016:
    algo: 3
    scheme: 3
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: "cylinder"
  file: cylinder.body
  kinematics:
    U0: -1.0
    V0: 0.0
