# 503x352 (177056)
mesh:
- direction: x
  start: -16.5
  subDomains:
  - cells: 21
    end: -8.1
    stretchRatio: 1.0
  - cells: 71
    end: -5.0
    stretchRatio: 0.9803921569
  - cells: 300
    end: 1.0
    stretchRatio: 1.0
  - cells: 93
    end: 6.3
    stretchRatio: 1.02
  - cells: 18
    end: 13.5
    stretchRatio: 1.0
- direction: y
  start: -15.0
  subDomains:
  - cells: 15
    end: -9.0
    stretchRatio: 1.0
  - cells: 111
    end: -1.0
    stretchRatio: 0.9803921569
  - cells: 100
    end: 1.0
    stretchRatio: 1.0
  - cells: 111
    end: 9.0
    stretchRatio: 1.02
  - cells: 15
    end: 15.0
    stretchRatio: 1.0

flow:
  nu: 0.025
  initialVelocity: [0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: yMinus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 0.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.001
  startStep: 0
  nt: 3500
  nsave: 500
  nrestart: 3500
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  delta: PESKIN_2002
  lietal2016:
    algo: 3
    scheme: 3
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: "cylinder"
  file: cylinder.body
  kinematics:
    U0: -1.0
    V0: 0.0

probes:
- name: probe-u
  type: VOLUME
  field: u
  viewer: hdf5
  path: probe-u.h5
  box:
    x: [-4.0, 1.0]
    y: [-0.5, 0.5]
