# 874x711 (621414)
mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 93
    end: -3.3263598326
    stretchRatio: 1.0
  - cells: 63
    end: -0.75
    stretchRatio: 0.9523809524
  - cells: 239
    end: 0.75
    stretchRatio: 1.0
  - cells: 303
    end: 12.9079497908
    stretchRatio: 1.01
  - cells: 176
    end: 35.0
    stretchRatio: 1.0
- direction: y
  start: -25.0
  subDomains:
  - cells: 173
    end: -3.2845188285
    stretchRatio: 1.0
  - cells: 63
    end: -0.75
    stretchRatio: 0.9523809524
  - cells: 239
    end: 0.75
    stretchRatio: 1.0
  - cells: 63
    end: 3.2845188285
    stretchRatio: 1.05
  - cells: 173
    end: 25.0
    stretchRatio: 1.0

flow:
  nu: 0.025
  initialVelocity: [1.0, 0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 1.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.01
  startStep: 0
  nt: 5000
  nsave: 1000
  nrestart: 5000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  delta: PESKIN_2002
  lietal2016:
    algo: 1
    scheme: 3
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: cylinder
  file: cylinder.body

probes:
- name: probe-p
  type: VOLUME
  field: p
  viewer: hdf5
  path: probe-p.h5
  n_sum: 1000
  box:
    x: [-0.75, 0.75]
    y: [-0.75, 0.75]
