flow:
  nu: 0.012732365673542143
  initialVelocity: [0.0, 0.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: xPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: yMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: zMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: zPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]

mesh:
  - direction: x
    start: -2.0
    subDomains:
      - end: 2.0
        cells: 256
        stretchRatio: 1.0
  - direction: y
    start: -2.0
    subDomains:
      - end: 2.0
        cells: 256
        stretchRatio: 1.0
  - direction: z
    start: -2.0
    subDomains:
      - end: 2.0
        cells: 256
        stretchRatio: 1.0

parameters:
  dt: 0.00157
  startStep: 0
  nt: 2500
  nsave: 100
  nrestart: 500
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  delta: ROMA_ET_AL_1999
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info
  lietal2016:
    algo: 1
    scheme: 3

bodies:
  - type: points
    name: "sphere"
    file: sphere.body
    kinematics:
      f: 1.2732395447351628
      Am: 0.125
      center: [0.0, 0.0, 0.0]

probes:
- name: probe-p
  type: VOLUME
  field: p
  viewer: hdf5
  path: /mnt/solution/probe-p.h5
  t_start: 3.14
  n_monitor: 10
  box:
    x: [-0.75, 0.75]
    y: [-0.75, 0.75]
    z: [-0.75, 0.75]
